### PR TITLE
Upgrade clang format for 120 chars line

### PR DESCRIPTION
**Pull request by EtienneAr**
I put 120 because I didn't want to be too greedy... Though, if you want to put more, I will not stop you (to say the least).

### CODE REVIEW

**Comment by EtienneAr** [comment]
I also added the rule to put `{` on a new line after function definition

**Comment by ManifoldFR** [comment]
> I also added the rule to put `{` on a new line after function definition

Not a fan personally

**Comment by ManifoldFR** [comment]
Would you like to re-format the files in your PR #16 ?

**Comment by EtienneAr** [comment]
I propose to copy the pinocchio style for unity across our projects :
https://github.com/stack-of-tasks/pinocchio/blob/master/.clang-format

After talking with @jorisv (who made it) I suggest 2 small changes :
- line length of 120 chars (instead of 100)
- `SortIncludes` set to `true`. This doesn't mean that we cannot sort includes anymore, but we will have to do it consciously, by separating each block with an empty line.

**Comment by ManifoldFR** [comment]
Makes sense to me. Good to merge?

**Comment by EtienneAr** [comment]
Yss ! :ok_hand:

**Pull request merged**
