### PR TITLE
Topic/refactor robothandler

### PR DESCRIPTION
**Pull request by EtienneAr**
Hello guys,

I did a substantial refactor on robot handler. It is now split into `RobotModelHandler` (for immutable data, such as robot model) and `RobotDataHandler` (for mutable data)

I updated the bindings, tests and benchmarks.

However, we do not have test in python, so I am not sure of what I broke in the python API...

Cheers

### CODE REVIEW

**Comment by ManifoldFR** [comment]
Looks good to me

**Review by ManifoldFR — APPROVED** [review]
This means that several classes now hold both the robot model and robot data handlers, from what I see.

lgtm

**Comment by EtienneAr** [comment]
This PR is ready for merge, all testes passes on my machine :)

**Comment by ManifoldFR** [comment]
I trust you on this

**Pull request merged**
